### ISSUE TITLE
Backslash not working

### ISSUE THREAD

**Issue by xXZweisteinXx** [Neradoc/Circuitpython_Keyboard_Layouts#11]
I am working with the german layout. 
It works fine, except for the backslash. 

I write:
STRING \

But the result is:
`

Can I change or add this in the script?

**Comment by Neradoc** [comment]
Hmmm I'm seeing the correct character with `STRING \` with the current version of the layout and pico ducky.

**Comment by xXZweisteinXx** [comment]
Unfortunately, it does not work for me. 

How could I replace or add a character?

**Comment by Neradoc** [comment]
Are you sure you are using the latest versions of each of the modules and no older one is lingering ?
Can you check what keyboard layout matches yours on this site ? https://kbdlayout.info/
Is it this one with the `\` on `altgr`-`ß` ? https://kbdlayout.info/kbdgr

You can see that `\` is the same keycode as ß, but is marked as using altgr as expected:
https://github.com/Neradoc/Circuitpython_Keyboard_Layouts/blob/f79c92185ee7d5bbb95c91901642ffca9a04d084/libraries/layouts/keyboard_layout_win_de.py#L108
https://github.com/Neradoc/Circuitpython_Keyboard_Layouts/blob/f79c92185ee7d5bbb95c91901642ffca9a04d084/libraries/layouts/keyboard_layout_win_de.py#L150
https://github.com/Neradoc/Circuitpython_Keyboard_Layouts/blob/f79c92185ee7d5bbb95c91901642ffca9a04d084/libraries/layouts/keyboard_layout_win_de.py#L145

The format used is as follows:
- low ascii characters have their keycode in the `ASCII_TO_KEYCODE` bytestring in their respective place, with the high bit set if it needs shift
- characters that also need altgr are in the `NEEDS_ALTGR` string
- high ascii characters that can't be in the table are in a dictionary of their own
- combined keys (like `^`+`u` = `û`) are encoded in a separate list

Pico ducky doesn't allow it in the payload format, but you can send keycodes directly in python with for example:
```py
kbd.send(0xE6, 0x2D)
```
Which send `altgr`+`ß` and should result in a `\\`
