### ISSUE TITLE
Can I Use This In My Repository?

### ISSUE THREAD

**Issue by detherminal** [Neradoc/Circuitpython_Keyboard_Layouts#13]
You don't have any license, can I use this in my [repository?](https://github.com/detherminal/Pico-Scripts). If you grant me, I will reference you in readme file.

**Comment by Neradoc** [comment]
Oh yeah some files are missing the header, I need to look into adding that, and the overall license info, but you can assume MIT everywhere:
```py
# SPDX-FileCopyrightText: 2021 Neradoc NeraOnGit@ri1.fr
#
# SPDX-License-Identifier: MIT
```

**Comment by detherminal** [comment]
Thanks
