### ISSUE TITLE
curly braces not working on the Italian keyboard

### ISSUE THREAD

**Issue by flalugli** [Neradoc/Circuitpython_Keyboard_Layouts#21]
Hello, i can't seem to get the curly braces "{}" working on the italian keyboard, i was trying to use them but i get this error
`ValueError: No keycode available for character '{' (123/0x7b)`

**Comment by Neradoc** [comment]
Ah, I see, can you test this version ?
https://raw.githubusercontent.com/Neradoc/Circuitpython_Keyboard_Layouts/fix-braces-it/libraries/layouts/keyboard_layout_win_it.py

**Comment by flalugli** [comment]
Thanks, it works!
