### ISSUE TITLE
Cannot generate the FR-Bépo layout

### ISSUE THREAD

**Issue by Chimrod** [Neradoc/Circuitpython_Keyboard_Layouts#25]
Hello,

I’m reporting this issue here but it is not reletive with CicuitPython directly: the issue comes from the tool provided for creating custom layout.

I’m trying to create the layout for [kbdfrnb](https://kbdlayout.info/kbdfrnb), but the [web application](https://www.neradoc.me/layouts/make_zip_bundle.php?url=https://kbdlayout.info/kbdfrnb&cpversion=) raises an error :

```
The source could not be interpreted, or is not supported, check the spelling.
https://kbdlayout.info/kbdfrnb
data/kbdlayout-info-frnb.xml
Error Layout

Error Keycodes
```

**Comment by Neradoc** [comment]
As it turns out, the layout contains double modifier keys, which are not currently supported, nor properly ignored by the 
Things like `ű ȁ` or the indices here:
```xml
      <Result With="VK_CONTROL VK_MENU">
        <DeadKeyTable Accent="ᵉ" Name="Exposants">
          <Result Text="⁰" With="0" />
          <Result Text="¹" With="1" />
          <Result Text="²" With="2" />
          <Result Text="³" With="3" />
          <Result Text="⁴" With="4" />
          <Result Text="⁵" With="5" />
          <Result Text="⁶" With="6" />
          <Result Text="⁷" With="7" />
          <Result Text="⁸" With="8" />
          <Result Text="⁹" With="9" />
          <Result Text="⁽" With="(" />
          <Result Text="⁾" With=")" />
          <Result Text="⁺" With="+" />
          <Result Text="⁻" With="-" />
          <Result Text="⁼" With="=" />
          <Result With="ᵉ">
            <DeadKeyTable Accent="ᵢ" Name="Indices">
              <Result Text="₀" With="0" />
              <Result Text="₁" With="1" />
              <Result Text="₂" With="2" />
              <Result Text="₃" With="3" />
              <Result Text="₄" With="4" />
              <Result Text="₅" With="5" />
              <Result Text="₆" With="6" />
              <Result Text="₇" With="7" />
              <Result Text="₈" With="8" />
              <Result Text="₉" With="9" />
              <Result Text="₍" With="(" />
              <Result Text="₎" With=")" />
              <Result Text="₊" With="+" />
              <Result Text="₋" With="-" />
              <Result Text="₌" With="=" />
              <Result Text="ᵢ" With=" " />
            </DeadKeyTable>
          </Result>
          <Result Text="ᵉ" With=" " />
        </DeadKeyTable>
      </Result>
```
Implementing them would be a piece of work, but ignoring them for now can generate some layout.
How do these work out ?
[frnb.zip](https://github.com/Neradoc/Circuitpython_Keyboard_Layouts/files/11468808/frnb.zip)

**Comment by Chimrod** [comment]
From the [bepo wiki](https://bepo.fr/wiki/Manuel#Exposants_et_indices)

> Vous pouvez obtenir les chiffres et la majorité des lettres en exposant et indice grâce à la touche morte « exposant » par simple ou double (pour les indices) pression de cette dernière. La touche morte « exposant » se fait avec [AltGr](https://bepo.fr/wiki/Glossaire#AltGr)+t.
>

which I can translate as:

You can get the numbers and most of the letters in exponent and subscript with the dead key "exponent" by simple or double (for subscripts) pressure of the latter. The "exponent" dead key is pressed with AltGr+t.

So `^t2`will produce `²` but  `^t^t2` will send `₂` 

It’s ok to ignore them, this is very a specific use case :)

**Comment by Neradoc** [comment]
Did you test the layout and keycodes in the previous message ?
I put them here too: https://gist.github.com/Neradoc/19c0faa3bd3b0d15ee530987a0093323

**Comment by Chimrod** [comment]
I’ve only tested `keycode_win_frnb.py` and this works fine. (I’ve made it works with or without modifier without any issue).

Thanks for your answer and the provided file!
