### ISSUE TITLE
Add support for the Brazilian Portuguese keyboard layout (ABNT2)

### ISSUE THREAD

**Issue by peterfritz** [Neradoc/Circuitpython_Keyboard_Layouts#3]
Hi, I'm trying to map the pt-BR keyboard layout but I couldn't figure out how to do so.

I found [this website](http://kbdlayout.info/kbdbr/scancodes) that lists the Scancodes for my keyboard, I then copied the preexisting French keyboard to change the codes so they match the ones in the website, but soon saw that the German was completely different.

Is there a article or wiki with instructions on how to make a map like that? How could I use one of these layouts in a Raspberry Pico with Adafruit CircuitPython HID?

I'm sorry to bother you with this. 
Thanks in advance.

**Comment by Neradoc** [comment]
Oh yeah, I need to document what is in a layout and keycode file, and how to change them. The codes used are the USB scancodes (which are refered to as keycodes here), which are a different set than the scancodes listed on the site (known as Set 1, I believe).

I have been looking into automatic conversion from the layout data, specifically the "XML for processing" link on kbdlayout.info for windows. I might make it into a web tool. It doesn't handle "dead key" combinations yet, so to type `ñ` for example you do `write("~n")` but I don't expect anything that can be typed with a single key or combination of keys to be missing anymore.

For now, here are a layout and keycode files for the layout you linked. Put the files in your CIRCUITPY or lib directory.
You use it in the same way as the example in the readme.
Tell me how it works for you.
```py
import usb_hid
from adafruit_hid.keyboard import Keyboard
from keyboard_layout_win_br import KeyboardLayoutWinBr
keyboard = Keyboard(usb_hid.devices)
layout = KeyboardLayoutWinBr(keyboard)
layout.write("N~ao falo portugu^es.")  # (google translate)
```

[keyboard_layout_win_br.zip](https://github.com/Neradoc/Circuitpython_Keyboard_Layouts/files/7071075/keyboard_layout_win_br.zip)

**Comment by peterfritz** [comment]
Hi, sorry for the late response. I cannot thank you enough, you're awesome.

Regarding the layout, I was able to use it with the code you sent me, but not with [pico-ducky](https://github.com/dbisu/pico-ducky).
```
# input
ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890-_=+§!@#$%&*()\"\"\\

# expected output
ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890-_=+§!@#$%&*()""\

# output
aBCdEFGhiJkLmNoPQRSTUVWXyZabcdefghijklmnopqrstuvwxyz1234567890-_=+§!@#$%&8()"'\
```
`*` turns into `8` and `"` becomes `'` while being typed. 

```
# input
ç´a`a~a^a´A`A~A^A´e`e~e^e´E`E~E^E´i`i~i^i´I`I~I^I´o`o~o^o´O`O~O^O´u`u~u^u´U`U~U^U;:.,//\\\\

# expected output
çáàãâÁÀÃÂéèẽêÉÈẼÊíìĩîÍÌĨÎóòõôÓÒÕÔúùũûÚÙŨÛ;:.,//\\

# output
çáàãâÁÀÃÂéèẽêÉÈẼÊíìĩîÍÌĨÎóòõôÓÒÕÔúùũûÚÙŨÛ;:.,q/\\
```
`/` turns into `q` but everything else is perfectly fine

There's also this weird issue with capitalization where every time the pico gives a different result.
```
aBCdeFGHIJkLmnopQRStUVWxyz
AbcdEFgHiJKlMNopQRstUVWxyz
aBcDEfgHiJKLmNopqRstuvwxYz
abcdEfghijklmnOpqrstuVWxyz
abcDeFgHIJKlmNopqrStuvwxyz
abcdeFGhIJKLMNopqRsTuvwXyz
abCdeFghijklmnoPqrsTuvwxyz
abcDEfgHijkLMNOPqrStUvwxYz
abCdEFghIJkLmnOpQRSTuVWXyz
```

After two days trying to fix this issues and make it work with pico-ducky, I think part of the fault lies on my old notebook, maybe it can't keep up with the Raspberry Pico and ends up losing some keys (especially `alt gr` and `shift`). 

Anyway, this project is fantastic. As you can see, I'm not the best with keyboards and microcontrollers but I would love to contribute. Is there anything I can do to help?

**Comment by Neradoc** [comment]
Hmmm. The code sends 3 reports for "A" for example: press shift, press shit+A, release both. You could try modifying `keyboard_layout.py` by adding a small delay (like say `time.sleep(0.005)`) in the write method before it releases the keys (`self.keyboard.release_all()`), and try different values for the delay. Or add a delay after `self.keyboard.press(self.SHIFT_CODE)` to hold shift longer before sending A (and the same with RIGHT_ALT_CODE). (Don't forget to `import time` at the top).
