### ISSUE TITLE
Where to paste that code or how to change the keyboard layout using the pico as an HID?

### ISSUE THREAD

**Issue by Spyx34** [Neradoc/Circuitpython_Keyboard_Layouts#8]

**Comment by Neradoc** [comment]
Oh hi, sorry for the delay, are you looking for instructions like this ?
https://github.com/dbisu/pico-ducky/issues/10#issuecomment-910684858
Or more generic ones like the simpletest ?
https://github.com/Neradoc/Circuitpython_Keyboard_Layouts/blob/main/examples/simpletest.py
Here is a guide on the basics of HID with Circuitpython.
https://learn.adafruit.com/circuitpython-essentials/circuitpython-hid-keyboard-and-mouse
