### ISSUE TITLE
Trying to change my default US layout to SP layout 

### ISSUE THREAD

**Issue by GuillemRX** [Neradoc/Circuitpython_Keyboard_Layouts#9]
I'm trying to create a USB Rubber Ducky with Raspberry Pi Pico following this tutorial: https://www.youtube.com/watch?v=e_f9p-_JWZw&t=472s

The thing is i've tried to get your layout and keycode for SP keyboard, move both file to the raspberry pico lib folder, and i've also changed code.py as you suggested on this post: https://github.com/dbisu/pico-ducky/issues/10#issuecomment-910684858

When I've done everything, my code.py corrupted and could do anything else. What am I doing wrong?

Thanks for your time.

Regards,

Guillem

**Comment by Neradoc** [comment]
Corrupted ? Like, the content of the file is messed up ? Or do you just mean it doesn't execute ?

There's 3 files to copy (py or mpy version)

- keyboard_layout.py
- keyboard_layout_win_sp.py
- keycode_win_sp.py

You can see if there's an error printed out to the serial console:
https://learn.adafruit.com/welcome-to-circuitpython/kattni-connecting-to-the-serial-console

If you can use discord, it's the better place for support, #help-with-circuitpython on the [adafruit discord](https://discord.gg/adafruit). (No private messages).

**Comment by GuillemRX** [comment]
I was missing the keyboard_layout.py... Somehow I didn't read that this file should've been moved to the raspberryxd. Thx for your help.

Btw do you know how to prevent the rubber ducky script from running every time it's plugged in?

Thx for your help mate
